// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-xxeast-1",
    "aws_appsync_graphqlEndpoint": "https://7yvnaxxepmu.appsync-api.ap-xxeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-xxeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_region": "ap-xxeast-1",
    "aws_user_pools_id": "ap-xxeast-1_dtZZy4cvs",
    "aws_user_pools_web_client_id": "4j1qxxj2r8qf"
};


export default awsmobile;
