// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://lumeorm3crfuzdkdremiyvlqoi.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-me65ambirvgplggkadprz56y3i",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_dtZZy4cvs",
    "aws_user_pools_web_client_id": "4j1qpntllshaab89stblj2r8qf",
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
